package com.averycorp.prismtask.data.export

import android.content.ContentValues
import android.content.Context
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.os.Environment
import android.provider.MediaStore
import com.averycorp.prismtask.domain.usecase.ClinicalReport
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import javax.inject.Inject
import javax.inject.Singleton

/**
 * On-device PDF writer for the v1.4.0 V8 clinical report.
 *
 * Walks the structured [ClinicalReport.sections] list and renders each
 * section header + its body lines to an A4 page using `PdfDocument`.
 * Multi-page reports are supported — the writer starts a new page when
 * the cursor runs off the bottom margin.
 *
 * The file is saved to `Downloads/PrismTask/` via MediaStore on API 29+
 * and directly to external storage on older APIs. The returned [Uri]
 * can be handed to an Android share intent.
 */
@Singleton
class ClinicalReportPdfWriter @Inject constructor() {

    /**
     * Render [report] to a PDF saved in the user's Downloads folder and
     * return its [Uri]. Returns null on any I/O failure so the caller can
     * surface a generic "Could not export report" snackbar without
     * needing to understand the PDF stack.
     */
    fun write(context: Context, report: ClinicalReport): Uri? {
        val document = PdfDocument()
        try {
            val pageWidth = 595
            val pageHeight = 842
            val margin = 40f
            var pageNumber = 1
            var pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
            var page = document.startPage(pageInfo)
            var canvas = page.canvas
            val headerPaint = Paint().apply {
                textSize = 18f
                isFakeBoldText = true
                color = android.graphics.Color.BLACK
            }
            val subtitlePaint = Paint().apply {
                textSize = 11f
                color = android.graphics.Color.DKGRAY
            }
            val sectionPaint = Paint().apply {
                textSize = 14f
                isFakeBoldText = true
                color = android.graphics.Color.BLACK
            }
            val bodyPaint = Paint().apply {
                textSize = 11f
                color = android.graphics.Color.BLACK
            }
            val footerPaint = Paint().apply {
                textSize = 9f
                color = android.graphics.Color.GRAY
            }

            var cursorY = margin
            canvas.drawText(report.title, margin, cursorY + 18f, headerPaint)
            cursorY += 28f
            canvas.drawText(report.subtitle, margin, cursorY + 11f, subtitlePaint)
            cursorY += 24f

            for (section in report.sections) {
                if (cursorY + 60f > pageHeight - margin) {
                    document.finishPage(page)
                    pageNumber++
                    pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
                    page = document.startPage(pageInfo)
                    canvas = page.canvas
                    cursorY = margin
                }
                canvas.drawText(section.header, margin, cursorY + 14f, sectionPaint)
                cursorY += 22f
                for (line in section.lines) {
                    if (cursorY + 14f > pageHeight - margin) {
                        document.finishPage(page)
                        pageNumber++
                        pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
                        page = document.startPage(pageInfo)
                        canvas = page.canvas
                        cursorY = margin
                    }
                    canvas.drawText("  $line", margin, cursorY + 11f, bodyPaint)
                    cursorY += 15f
                }
                cursorY += 10f
            }

            // Footer on the final page.
            val footer = "Generated by PrismTask. Not a medical document."
            if (cursorY + 20f > pageHeight - margin) {
                document.finishPage(page)
                pageNumber++
                pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
                page = document.startPage(pageInfo)
                canvas = page.canvas
                cursorY = margin
            }
            canvas.drawText(footer, margin, (pageHeight - margin + 10f), footerPaint)
            document.finishPage(page)

            val fileName = "prismtask-report-${SimpleDateFormat("yyyyMMdd-HHmm", Locale.US).format(Date())}.pdf"
            return saveViaMediaStore(context, document, fileName)
                ?: saveToExternal(context, document, fileName)
        } catch (t: Throwable) {
            return null
        } finally {
            document.close()
        }
    }

    private fun saveViaMediaStore(context: Context, document: PdfDocument, fileName: String): Uri? {
        if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.Q) return null
        return try {
            val values = ContentValues().apply {
                put(MediaStore.Downloads.DISPLAY_NAME, fileName)
                put(MediaStore.Downloads.MIME_TYPE, "application/pdf")
                put(MediaStore.Downloads.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS + "/PrismTask")
            }
            val resolver = context.contentResolver
            val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, values) ?: return null
            resolver.openOutputStream(uri)?.use { out ->
                document.writeTo(out)
            } ?: return null
            uri
        } catch (_: Throwable) {
            null
        }
    }

    private fun saveToExternal(context: Context, document: PdfDocument, fileName: String): Uri? {
        return try {
            val dir = File(
                Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS),
                "PrismTask"
            )
            if (!dir.exists()) dir.mkdirs()
            val file = File(dir, fileName)
            FileOutputStream(file).use { out -> document.writeTo(out) }
            Uri.fromFile(file)
        } catch (_: Throwable) {
            null
        }
    }
}
